Examen T3/Models/ErrorViewModel.cs
using System;

namespace Examen_T3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examen T3/Models/Especie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_T3.Models
{
    public class Especie
    {
        public int Id { set; get; }
        public string Nombre { set; get; }
        public List<Raza> Razas { set; get; }
    }
}

Examen T3/Models/HistoriaClinica.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_T3.Models
{
    public class HistoriaClinica
    {
        public int Id { set; get; }
        [Required]
        public DateTime FechaRegistro { set; get; }
        [Required]
        public string Nombre { set; get; }
        [Required]
        public DateTime Nacimiento { set; get; }
        [Required]
        public string Sexo { set; get; }
        [Required]
        public string Especie { set; get; }
        [Required]
        public string Raza { set; get; }
        [Required]
        public int Tamaño { set; get; }
        [Required]
        public string Datos { set; get; }
        [Required]
        public string Dueño { set; get; }
        [Required]
        public string Direccion { set; get; }
        [Required]
        public string Telefono { set; get; }
        [Required]
        public string Email { set; get; }
    }
}

Examen T3/Models/Raza.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_T3.Models
{
    public class Raza
    {
        public int Id { set; get; }
        public string Nombre { set; get; }
        public Especie Especie { set; get; }
        public int IdEspecie { set; get; }
    }
}

Examen T3/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_T3.Models
{
    public class Usuario
    {
        public int Id { set; get; }
        public string Username { set; get; }
        public string Password { set; get; }
    }
}

Examen T3/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Examen_T3.Repositories;
using Examen_T3.Services;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Examen_T3.Controllers
{

        public class AuthController : Controller
        {
            private readonly IUsuarioRepository repository;
            private readonly ICookieAuthService cookieService;
            public AuthController(IUsuarioRepository repository, ICookieAuthService cookieService)
            {
                this.repository = repository;
                this.cookieService = cookieService;
            }

            [HttpGet]
            public IActionResult Login()
            {
                return View();
            }
            [HttpPost]
            public IActionResult Login(string Username, string Password)
            {

                var usuariodb = repository.FindUserLogin(Username, Password);
                if (usuariodb == null)
                {
                    ModelState.AddModelError("Usuario", "Usuario y/o contraseña incorrectos");
                    return View();
                }
                cookieService.SetHttpContext(HttpContext);
                cookieService.SetSessionContext(usuariodb);
                var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name,usuariodb.Username)
                    };

                var Identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(Identity);

                cookieService.Login(principal);
                return RedirectToAction("Index", "Home");
            }

            [Authorize]
            [HttpGet]
            public IActionResult Logout()
            {
                cookieService.SetHttpContext(HttpContext);
                cookieService.LogOut();
                return RedirectToAction("Index", "Home");
            }
        }
    
}

Examen T3/Controllers/HistoriaClinicaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Examen_T3.Models;
using Examen_T3.Repositories;
using Examen_T3.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Examen_T3.Controllers
{
    [Authorize]
    public class HistoriaClinicaController : Controller
    {
        private readonly IHistoriaClinicaRepository repository;
        private readonly ICookieAuthService cookieService;
        public HistoriaClinicaController(IHistoriaClinicaRepository repository, ICookieAuthService cookieService)
        {
            this.repository = repository;
            this.cookieService = cookieService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var hc = repository.ListaHistoriasClinicas(); 
            return View(hc);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Especies = repository.GetEspecies();
            return View(new HistoriaClinica());
        }
        [HttpPost]
        public IActionResult Create(HistoriaClinica hc)
        {
            
            if (hc == null)
                ModelState.AddModelError("Nombre", "Datos incorrectos");
            
            //if((repository.findHCSimilares(hc.Dueño)).Count() > 0)
            //    ModelState.AddModelError("Dueño", "No puede haber más de un dueño");
            
            if (ModelState.IsValid)
            {
                repository.AddHistoriaClinica(hc);
                return RedirectToAction("Index");
            }
            return View(hc);
        }
        public IActionResult Razas(int IdEspecie)
        {
            var razas = repository.GetRazas(IdEspecie);
            return View(razas);
        }
        [HttpGet]
        public IActionResult Mostrar(int Id)
        {
            var hc = repository.HistoriaClinicaEspecifico(Id);
            return View(hc);
        }

    }
}

Examen T3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Examen_T3.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Examen T3/Views/HistoriaClinica/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<div class="card h-75 mt-lg-5">
    <div class="text-center mt-3 mb-3">
        <h3 class="card-title text-dark font-weight-bold"> Ficha de Realizacion de prueba</h3>
    </div>
    <form action="/HistoriaClinica/Create" method="post">

        <div class="row my-3 mx-3">
            <div class="col-xs-4 ml-3">
                <label>Fecha de registro</label>
                <input type="date" class="form-control" name="FechaRegistro" max="2020-11-04" value="@Model.FechaRegistro" />
                @Html.ValidationMessage("FechaRegistro")
            </div>
            <div class="col-xs-6 ml-3">
                <div class="row ml-5">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label>Sexo</label>
                        </div>

                        <div class="col-md-12 ml-1">
                            <select name="Sexo" class="custom-select">
                                <option selected disabled>-- Opciones --</option>
                                <option value="Masculino">Masculino</option>
                                <option value="Femenino">Femenino</option>
                            </select>
                            @Html.ValidationMessage("Sexo")
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-1 ml-1"></div>
            <div class="col-md-3 ml-1">
                <label>Fecha de Nacimiento</label>
                <input type="date" class="form-control" name="Nacimiento" max="2020-11-04" value="@Model.Nacimiento" />
                @Html.ValidationMessage("Nacimiento")
            </div>
        </div>
        <div class="row my-3 mx-3">
            <div class="col-xs-4 ml-3">
                <label>Nombre de la mascota</label>
                <input type="text" class="form-control" name="Nombre" value="@Model.Nombre" />
                @Html.ValidationMessage("Nombre")
            </div>
            <div class="col-xs-6 ml-3">
            </div>
            <div class="col-xs-4 ml-3">
                <label>Tamaño (en cm)</label>
                <input type="text" class="form-control" name="Tamaño" value="@Model.Tamaño" />
                @Html.ValidationMessage("Tamaño")
            </div>
        </div>
        <div class="row my-1 mx-3">
            <div class="col-xl-3">
                <label>Especie</label>
            </div>
            <div class="col-xl-3">
                <label>Raza</label>
            </div>
        </div>
        <div class="row my-1 mx-5">
            <div class="form-group row">
                <div class="col-xs-8">
                    <select name="Especie" class="custom-select" id="Especie">
                        <option>-- Seleccione Valor --</option>
                        @foreach (var item in ViewBag.Especies)
                        {
                            <option value="@item.Id">@item.Nombre</option>
                        }
                    </select>
                </div>
                <div id="Razas">
                </div>
            </div>
        </div>
        <div class="row my-1 mx-3">
            <div class="col-xl-12">
                <label>Datos particulares</label>
            </div>
            <div class="col-xl-8">
                <textarea name="Datos" class="form-control"></textarea>
                @Html.ValidationMessage("Datos")
            </div>
        </div>
        <div class="text-left mt-1 mb-3 mx-4 my-4">
            <h3 class="card-title text-dark font-weight-bold">Datos del dueño</h3>
        </div>
        <div class="row mx-3 my-3">
            <div class="col-xl-6">
                <label>Nombre</label>
            </div>
            <div class="col-xl-6">
                <label>Direccion</label>
            </div>
        </div>
        <div class="row mx-3 my-3">
            <div class="col-xl-6">
                <input type="text" name="Dueño" class="form-control" value="@Model.Dueño" />
                @Html.ValidationMessage("Dueño")
            </div>
            <div class="col-xl-6">
                <input type="text" name="Direccion" class="form-control" value="@Model.Direccion" />
                @Html.ValidationMessage("Direccion")
            </div>
        </div>
        <div class="row mx-3 my-3">
            <div class="col-xl-6">
                <label>Telefono</label>
            </div>
            <div class="col-xl-6">
                <label>Email</label>
            </div>

        </div>
        <div class="row mx-3 my-3">
            <div class="col-xl-6">
                <input type="tel" name="Telefono" class="form-control" value="@Model.Telefono" />
                @Html.ValidationMessage("Telefono")
            </div>
            <div class="col-xl-6">
                <input type="email" name="Email" class="form-control" value="@Model.Email" />
                @Html.ValidationMessage("Email")
            </div>

        </div>
        <div class="row my-5 mx-3">
            <div class="col-xl-12 text-center">
                <button class="btn btn-success"><i class="fas fa-save"></i> Guardar</button>
            </div>
        </div>
    </form>

</div>

<script>

    function init() {
        $.ajax({
            url: '/historiaClinica/Razas?IdEspecie=' + $('#Especie').val()
        }).done(function (Tablex) {
            $('#Razas').html(Tablex)
        });
    }

    $(document).ready(function () {
        $("#Especie").on('change',function () {
            init();
        });
    });

</script>

Examen T3/Views/HistoriaClinica/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<div class="text-center mt-3 mb-3">
    <h3 class="card-title text-dark font-weight-bold">Veterinaria Patitas</h3>
</div>
<div class="text-right">
    <br />
    <a href="/historiaClinica/create" class="btn btn-primary">Nueva Historia Clinica</a>
    <br />
</div>
<table class="table table-dark">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Dueño</th>
            <th scope="col">Telefono</th>
            <th scope="col">Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>@item.Dueño</td>
                <td>@item.Telefono</td>
                <td>@item.Email</td>
                <td><a href="/HistoriaClinica/Mostrar?Id=@item.Id" class="btn btn-success">Ver</a></td>
            </tr>
        }
    </tbody>
</table>

Examen T3/Views/HistoriaClinica/Mostrar.cshtml
@{
    ViewData["Title"] = "Mostrar";
}
<div class="text-center mt-3 mb-3 mx-4 my-4">
    <h2 class="card-title text-dark font-weight-bold">Veterinaria Patitas</h2>
</div>
<div class="card h-75 mt-lg-5">
    <div class="text-left mt-3 mb-3 mx-4">
        <h3 class="card-title text-dark font-weight-bold">Historia Clinica</h3>
    </div>
    <div class="row my-3 mx-3">
        <div class="col-xs-4 ml-3">
            <label>Fecha de registro</label>
            <h6>@Model.FechaRegistro</h6>
        </div>
        <div class="col-xs-6 ml-3">
            <div class="row ml-5">
                <div class="form-group row">
                    <div class="col-md-12">
                        <label>Sexo</label>
                    </div>

                    <div class="col-md-12 ml-1">
                        <h6>@Model.Sexo</h6>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-1 ml-1"></div>
        <div class="col-md-3 ml-1">
            <label>Fecha de Nacimiento</label>
            <h6>@Model.Nacimiento</h6>
        </div>
    </div>
    <div class="row my-3 mx-3">
        <div class="col-xs-4 ml-3">
            <label>Nombre de la mascota</label>
            <h6>@Model.Nombre</h6>
        </div>
        <div class="col-xs-6 ml-3">
        </div>
        <div class="col-xs-4 ml-3">
            <label>Tamaño (en cm)</label>
            <h6>@Model.Tamaño</h6>
        </div>
    </div>
    <div class="row my-1 mx-3">
        <div class="col-xl-2">
            <label>Especie</label>
        </div>
        <div class="col-xl-2">
            <label>Raza</label>
        </div>
    </div>
    <div class="row my-1 mx-3">
        <div class="col-xl-2">
            <h6>@Model.Especie</h6>
        </div>
        <div class="col-xl-2">
            <h6>@Model.Raza</h6>
        </div>
    </div>
    <div class="row my-1 mx-3">
        <div class="col-xl-12">
            <label>Datos particulares</label>
        </div>
        <div class="col-xl-8">
            <h6>@Model.Datos</h6>
        </div>
    </div>
    <div class="text-left mt-1 mb-3 mx-4 my-4">
        <h3 class="card-title text-dark font-weight-bold">Datos del dueño</h3>
    </div>
    <div class="row mx-3">
        <div class="col-xl-6">
            <label>Nombre</label>
        </div>
        <div class="col-xl-6">
            <label>Direccion</label>
        </div>
    </div>
    <div class="row mx-3">
        <div class="col-xl-6">
            <h6>@Model.Dueño</h6>
        </div>
        <div class="col-xl-6">
            <h6>@Model.Direccion</h6>
        </div>
    </div>
    <div class="row mx-3">
        <div class="col-xl-6">
            <label>Telefono</label>
        </div>
        <div class="col-xl-6">
            <label>Email</label>
        </div>

    </div>
    <div class="row mx-3">
        <div class="col-xl-6">
            <h6>@Model.Telefono</h6>
        </div>
        <div class="col-xl-6">
            <h6>@Model.Email</h6>
        </div>

    </div>

</div>

Examen T3/Views/HistoriaClinica/Razas.cshtml
@{
    Layout = null;
}

    <div class="form-group row">
        <div class="col-xl-10 mx-5">
            <select class="form-control" name="Raza">
                @foreach (var item in Model)
                {
                    <option value="@item.Nombre">@item.Nombre</option>
                }
            </select>
        </div>
    </div>

Examen T3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Examen T3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen_T3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Examen_T3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HistoriaClinica" asp-action="Index">Historia Clinica</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Examen_T3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>